### ISSUE TITLE
關於maxHealth

### ISSUE THREAD

**Issue by jyhsu2000** [caoli5288/PlayerSQL#1]
請問有考慮支援maxHealth嗎？
有些插件會改變玩家的最大血量
重新計算最大血量的時機一般在等級改變時
但此插件會使最大血量在玩加上線時重新設定到20
因此建議新增maxHealth的支援

**Comment by caoli5288** [comment]
關於修改玩家最大血量的插件，之前有考慮過支援的，但最後撤銷了。
理由：同類插件很多，機制各異，由我(playersql)進行最大血量的保存、讀取易造成反復刷新最大血量的bug。
