### ISSUE TITLE
关于后台无限报错的问题

### ISSUE THREAD

**Issue by jiongjionger** [caoli5288/PlayerSQL#12]
在TimerCheckTask中的kick方法没有检查获取的用户是否为null，有极小的概率导致可能无限报错，并且使得TPS锐减直至蹦服。经过三天测试，发现修改后该问题得以解决。
修改后的方法代码：
private void kick(UUID uuid) {
		Player p = server.getPlayer(uuid);
		/*
		 * Possible offline here.
		 */
		if (p != null) {
			if (p.isOnline()) {
				p.kickPlayer(DataCompound.MESSAGE_KICK);
			}
		}
		compond.state(uuid, null);
	}

**Comment by caoli5288** [comment]
thx
