### ISSUE TITLE
Locked Players can't rejoin for a long time!

### ISSUE THREAD

**Issue by helptiger** [caoli5288/PlayerSQL#14]
In some circumstances a player gets kicked because of locked data (column Online = 1). Often he can't rejoin for a long time (for example 15 or 20 minutes) or until the server get's a restart.

You could test it, if you set your player (must be offline) manually to online in the MySQL table (column Online = 1) and then try to join the server.

My current workaround with this issue is a custom plugin that sets the player online boolean to 0 if the player is kicked from the server (to the hub)

**Comment by caoli5288** [comment]
Server and plugin version?

**Comment by helptiger** [comment]
server: 1.8.3 and 1.8.7; plugin: 1.1.2 from Spigot and 1.1.3 from here

**Comment by caoli5288** [comment]
Any server lag or crash before lock data?

**Comment by helptiger** [comment]
no, absolutely none

**Comment by caoli5288** [comment]
Any error output?

**Comment by helptiger** [comment]
no

**Comment by helptiger** [comment]
for me it seems that the unlock process is not fired correctly

**Comment by caoli5288** [comment]
I have no idea yet, I will test it this weekend.

**Comment by Dummyc0m** [comment]
> You could test it, if you set your player (must be offline) manually to online in the MySQL table (column Online = 1) and then try to join the server.
What?

**Comment by caoli5288** [comment]
I really found no problems in testing. 
I switched the server more than 100 times and not one failure.

**Comment by helptiger** [comment]
Hmm, but have you also tested what happens if a player is locked? For me the bug hides in the unlock process. That could be the UnlockTask.java or related. The simplest way to test is to manually set the player online to 0 in the db and than try to join. So again, what happens after a player is locked.

**Comment by caoli5288** [comment]
I know it will locked 5 mins.

**Comment by helptiger** [comment]
So, is it possible to reduce this time or make it configurable?

**Comment by Dummyc0m** [comment]
The plugin saves a player every 3 minutes i suppose, so 5 min lock is alright.

**Comment by Cnly** [comment]
> Hmm, but have you also tested what happens if a player is locked? For me the bug hides in the unlock process. That could be the UnlockTask.java or related. The simplest way to test is to manually set the player online to 0 in the db and than try to join. So again, what happens after a player is locked.

`UnlockTask.java` is only used in an infrequent case where a player quits the server fast enough after joining to unlock the locked data, which was locked during its data's being loaded.

> So, is it possible to reduce this time or make it configurable?

Which `time` do you mean?

**Comment by caoli5288** [comment]
Close. You can test the new "/psql send <who> <target_server>" command. If any problem please open a new issue.
