### ISSUE TITLE
Update from 1.08 to 1.17 errors

### ISSUE THREAD

**Issue by mariolars** [caoli5288/PlayerSQL#21]
Hi, i have follwing errors which spams my console.
http://pastebin.com/aR9b9TcA
PaperSpigot 1.7.10, with ProtocolLib 3.6.0 Snapshot.

**Comment by caoli5288** [comment]
Yes. newer playersql's itemstack serializer not(hard) depend protocollib(for 1.7-1.8 compatible reason).
So some compatible issues on it. Can not be fix.
