### ISSUE TITLE
Java 7 Compatibility

### ISSUE THREAD

**Issue by Phreag** [caoli5288/PlayerSQL#22]
Could you compile it also with java 7?

**Comment by caoli5288** [comment]
I'm sorry I used some of the java8 new features in the code, so I can't use the java7 compiler.
I strongly recommend that you use java8, which is extremely useful.

**Comment by Phreag** [comment]
I already fixed it myself. Just removed some lambda expressions Made it run with Java 7 petfectly

**Comment by caoli5288** [comment]
Good.
