### ISSUE TITLE
Easy improvement to avoid the "Datal Locked Error"

### ISSUE THREAD

**Issue by Phreag** [caoli5288/PlayerSQL#24]
I Would suggest to chnage its behavior to something different.

If a player joins the server, the plugin starts checking the date after n ticks. 
if it is locked, wait for n ticks and try again.
And it will do so on until the data is available or if it has tried it for x seconds.
This will improve the Performance much, because on most mysql servers the data should already be written when the player arrives on the server.

It that possible?

**Comment by caoli5288** [comment]
Yes. In some older versions I did that. In some of the reasons I gave up doing this.
In some older versions I did that.

**Comment by caoli5288** [comment]
@Phreag See v2.0-rc :+1:
