### ISSUE TITLE
MysqlDataTruncation: Data truncation: Data too long for column 'inventory' at row 1

### ISSUE THREAD

**Issue by SmilingTrickster** [caoli5288/PlayerSQL#29]
Some of the players have items with custom NBT tags in their inventory. Some of them are pretty complex. It looks like the String "version" of that inventory has exceeds the maximum length limit of the EBean Server. I'm not familiar with the Spigot EBean server utils, but I assume if you could change the column type to one that can hold more bytes?

**Comment by caoli5288** [comment]
You can set this column type to LONGTEXT manual.
> ALTER TABLE `playersql` MODIFY COLUMN `inventory`  longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL AFTER `exp`;
