### ISSUE TITLE
All those exceptions...

### ISSUE THREAD

**Issue by SmilingTrickster** [caoli5288/PlayerSQL#31]
玩家登陆时有时会报这个错，有一个玩家汇报说丢失了一大半的物品，只留下了几个，原因未明
这是该玩家在装了PlayerSQL后的第一次登陆，并且在登陆时立刻被杀死，复活时就没了大部分的背包和一半的盔甲，但是末影箱没有受影响
错误报告:
http://pastebin.com/Xd5Ja7Fu

**Comment by caoli5288** [comment]
整个背包数据是写在一个栏位，不存在丢失一部分。这个报错也与丢失物品无关，是玩家突然下线导致的。
