### ISSUE TITLE
compatible with combat log plugin

### ISSUE THREAD

**Issue by helptiger** [caoli5288/PlayerSQL#38]
I'm using a anti combat log plugin, that clears the playerinv on quit (while in combat). The event has a HIGH priority. With PlayerSQL the inventory is stored before it gets cleared, even if I compile it with a LOW priority on the PlayerQuitEvent. How could I make it compatible? Thx  

Combat PlayerQuitEvent:

    @EventHandler(ignoreCancelled = true, priority = EventPriority.HIGH)
    public void onQuit(PlayerQuitEvent e) {
        Player p = e.getPlayer();
        if (this.incombat.containsKey(p.getUniqueId())) {
            // broadcast...
            p.setHealth(0.0);
            p.setFoodLevel(0);
            p.getInventory().setHelmet(new ItemStack(Material.AIR));
            p.getInventory().setChestplate(new ItemStack(Material.AIR));
            p.getInventory().setLeggings(new ItemStack(Material.AIR));
            p.getInventory().setBoots(new ItemStack(Material.AIR));
            p.getInventory().clear();
            this.incombat.remove(p.getUniqueId());
        }
    }

PlayerSQL Test:

    @EventHandler(priority = LOWEST)
    public void handle(PlayerQuitEvent event) {
        UUID uuid = event.getPlayer().getUniqueId();
        if (manager.isNotLocked(uuid)) {
            manager.cancelTask(uuid);
            User user = manager.getUserData(event.getPlayer(), true);
            main.runTaskAsynchronously(() -> {
                manager.saveUser(user, false);
            });
        } else {
            manager.unlockUser(uuid, false);
        }
    }

**Comment by kaenganxt** [comment]
Lowest priority is executed first so the inventory is saved before your handler gets called. You need it the other way around :) (It's LOWEST -> LOW -> NORMAL -> HIGH -> HIGHEST -> MONITOR in that order)

**Comment by helptiger** [comment]
that was the case! I thought that highest priority comes first. Thanks for your help!

**Comment by caoli5288** [comment]
Maybe I need change it to HIGHEST...I think playersql should wait other plugin(s) process first.
