### ISSUE TITLE
Return double items when player logout of the game

### ISSUE THREAD

**Issue by mai1015** [caoli5288/PlayerSQL#39]
### Problem
When player logout of the game, some plugin returns double amount of items to player.
Such as DuanzaoCMD, SpecialAttributes

### Cause
I'm not sure whats causing this to happen, but plugins works perfectly well with out the plugin.

I guess it is the problem with the player lock... returning item after locking the player.
I will try it out later.

**Comment by caoli5288** [comment]
I think not. PlayerSQL do inventory clear before restore.

**Comment by jiongjionger** [comment]
Some plugins , especially have GUI interfaces , which can be put items into GUI. In order to prevent items placed in the GUI from being dropped when the GUI is closed . These items will add to the player's backpack but forgot to clear item in GUI , so in some cases will return double items , especially open these GUI interfaces when reboot server or close game client . So this is not caused by PlayerSQL.

**Comment by caoli5288** [comment]
PlayerSQL will block player's any inventory open action before restore done. :-)

**Comment by mai1015** [comment]
> Some plugins , especially have GUI interfaces , which can be put items into GUI. In order to prevent items placed in the GUI from being dropped when the GUI is closed . These items will add to the player's backpack but forgot to clear item in GUI , so in some cases will return double items , especially open these GUI interfaces when reboot server or close game client . So this is not caused by PlayerSQL.

Thats right, 
I try it on a server that only enables PlayerSQL and the plugin with GUI that return items when close. 
It always get double amount when I directly close the game client.

It does not have any thing to do with "inventory open action before restore done".

**Comment by mai1015** [comment]
我已经单独测试过插件了。
只要那个插件有GUI，而且关闭gui时候会返回物品。那么只要腐竹关闭服务器或者玩家直接关闭客户的，玩家就会获得双倍的物品。不是登陆的时候。

**Comment by caoli5288** [comment]
@mai1015 这个我得自己先测试下看看

**Comment by mai1015** [comment]
@caoli5288 恩我的测试环境是 Bukkit 1.7.10
如果需要我可以给你发下我的插件。

**Comment by caoli5288** [comment]
@mai1015 目前版本在玩家退出时，为了保证数据安全是会关闭玩家打开的窗口再进行数据读取的，如果有问题的话，我插件这边可能无能为力。

**Comment by jiongjionger** [comment]
@mai1015 举个例子，一个插件是一个GUI界面的物品收购插件，将物品放入这个GUI界面，并且点击GUI界面里的某个按钮来完成收购，但是插件为了防止玩家不小心直接关闭了GUI界面导致GUI界面里的物品丢失，往往插件作者会直接监听 InventoryCloseEvent 事件，如果玩家背包满了，掉落在地上（getPlayer().getWorld().dropItem），如果玩家背包没有满，放入玩家背包（getPlayer().getInventory().addItem）。但是他们往往忘记了一个很重要的事情，就是在这些操作以后删除GUI界面里面本来的那些物品（getInventory().clear(物品index)），这就是为什么会双倍物品的原因，这是这些插件的设计缺陷，而不是PlayerSQL的问题。

**Comment by mai1015** [comment]
@jiongjionger 需要清理掉物品吗？因为我看了代码是获取GUI里面物品的列表
然后在另外一个线程发到玩家的背包。主要是，当没有playersql的时候就不会出现这个问题
难道说，playersql导致GUI关闭两次？
另外，本来GUI里面不止玩家的物品，还有其他的装饰。这些物品都被插件忽略，不会发到玩家的背包。也没有其他插件会把这些东西发到玩家的背包，那如果不是两个插件配合的时候重复发了一次那是什么情况？

**Comment by mai1015** [comment]
但是还是谢谢了，我清理下物品试试看。

**Comment by caoli5288** [comment]
试一下2.5.1看看
