### ISSUE TITLE
我在用playersql遇到了一个很致命的问题

### ISSUE THREAD

**Issue by Wei-Boss** [caoli5288/PlayerSQL#44]
简单说:
A服务器是死亡掉落的,B服务器不掉落
玩家在A服务器快死的时候就立马跨服到B服务器
快死情况有: 着火/给追着打等等....
然后到了B服务器背包的物品全没了

然后我也是一个开发者
这个原因我也有猜想,因为BC跨服是先连接服务器,再断开连接
大概原因是玩家已经连接到B服务器了,但是A服务器还没退出就死了
我觉得这个问题需要BC插件应该才能解决吧。

**Comment by caoli5288** [comment]
你不应该在掉落与不掉落的服务器之间同步东西。

我建议你使用我的另一个插件，跨服末影箱进行同步。https://github.com/caoli5288/EnderChest
