### ISSUE TITLE
一些问题，希望可以修复

### ISSUE THREAD

**Issue by CNWilliamChang** [caoli5288/PlayerSQL#45]
问题：
1. 地图无法被同步。当在A服务器制作了地图以后，到B服务器，地图是空的

2. 生命值同步导致玩家直接死亡。例如A、B、C服务器里面，只有B关闭了生命值同步功能，会导致进入服务器后直接死亡

3. 有时候把物品放入箱子以后，去其他服务器再快速返回，背包里面会出现已经放入箱子的物品，导致可以刷物品。建议在一些敏感操作以后立刻保存/同步数据，或者可以增强一个BC/Redis的通讯功能，保证在其他服务器的同步操作晚于之前的保存操作。

**Comment by caoli5288** [comment]
> 地图无法被同步。当在A服务器制作了地图以后，到B服务器，地图是空的
需要更多信息，是否有报错？

> 生命值同步导致玩家直接死亡。例如A、B、C服务器里面，只有B关闭了生命值同步功能，会导致进入服务器后直接死亡
目前就是这样设定的，关于要不要同步0血量，我这里与一些用户做过讨论，得到的结论是同步0血量。

> 有时候把物品放入箱子以后，去其他服务器再快速返回，背包里面会出现已经放入箱子的物品，导致可以刷物品
我没能重现这个操作，请适当增大配置文件里面的plugin.delay的值。

> 或者可以增强一个BC/Redis的通讯功能，保证在其他服务器的同步操作晚于之前的保存操作
这个是胎死腹中的playersql-3.x的基础，设想中的架构是redis缓存+mysql回写+redis消息订阅，但是由于我们自己这边没有playersql所以停留在计划。

**Comment by JHXSMatthew** [comment]
地图那个有遇到过类似的情况，直接给地图会成空白地图。
解决方案；要么设置一下地图的metadata要么换成空白地图让玩家右键一下就好了。

**Comment by CNWilliamChang** [comment]
非常感谢你一直以来对插件的更新和维护。

1. 地图没有任何报错信息，重现步骤：在A服务器使用拿着空地图右键，生成一个有内容的地图，然后到B服务器，这个地图会不显示任何内容，变成空地图，地图丢失了NBT信息

2. 希望可以增加一个选项来决定是否同步0血量

3. 刷物品这个很难重现，需要运气，我自己试了很久也只出现了一次。应该是跨服的时候，读取数据在保存完毕之前导致的，我把延迟读取设置在5秒依然有这个现象

> 这个是胎死腹中的playersql-3.x的基础，设想中的架构是redis缓存+mysql回写+redis消息订阅，但是由于我们自己这边没有playersql了，所以停留在计划。

以后这个插件还会更新吗？国内外的使用量都挺大的。

**Comment by caoli5288** [comment]
地图保存图像不是以纯nbt保存，目前可能没有太大办法。以后会持续兼容新版本服务端。

**Comment by CNWilliamChang** [comment]
期待以后的基于redis消息的版本，相信可以彻底解决背包同步失效的问题

**Comment by caoli5288** [comment]
增加了是否处理0血量的选项。节点为`plugin.omit-player-death`，设置为`true`后，当同步到health=0时玩家的血量会被设置成max_health。

增加了基于pluginmessage进行快速同步数据的功能，将插件jar文件丢进bungeecord的插件目录即可。懒得做3.x了，先简单做做吧。
