### ISSUE TITLE
能不能做3天内的表备份

### ISSUE THREAD

**Issue by li709** [caoli5288/PlayerSQL#7]
如题，有一些情况下。会导致背包莫名其妙清空。或者还原物品。
但这样同样会同步到sql里。。
我想的是做个定时任务。按N小时备份表。保留N天内的表。这样。就可以在清空背包的情况下。恢复背包了。
还需要个恢复功能？
0.0就这样

**Comment by jiongjionger** [comment]
表示有时候玩家退出的时候背包并没有成功保存

**Comment by caoli5288** [comment]
然而想备份并不需要插件来做。
