### ISSUE TITLE
2.11.6会导致无限刷物品

### ISSUE THREAD

**Issue by nicklly** [caoli5288/PlayerSQL#71]
服务器核心：paper-1.12.2-1618
JAVA版本：1.8.144
playerSQL版本：v2.11.6
simpleorm-1.3-SNAPSHOT

玩家将物品存放进上了牌子锁的箱子后，退出大厅后再进入服务器，背包里会刷出跟箱子里一样数量的物品
退出大厅显示由于playersql_magic_kick，你被踢出了服务器
![K% 1DN$Q`0 CHS0`S)18I~Q](https://user-images.githubusercontent.com/17716585/129574062-1cc319af-c932-4a1d-af6b-6e7a293463ba.png)

![0A25068295037E49ECE8FD1FAFD78529](https://user-images.githubusercontent.com/17716585/129572715-59861270-54da-421a-b2ef-5a6351d3e38f.png)

**Comment by caoli5288** [comment]
bungee上也装了么，去掉bungee上的试试，看上去是冲突了

**Comment by nicklly** [comment]
> bungee上也装了么，去掉bungee上的试试，看上去是冲突了

bc没有装playersql  单服务端装上去配置完了之后重启服务器  重复上述步骤就出现箱子里的物品回到了身上的问题

**Comment by caoli5288** [comment]
无法复现。`playersql_magic_kick`是装了bungee侧插件才会启用的功能，如果你确实没装，但是意外启用了这功能，那肯定是跟其他什么插件冲突了，无能为力

**Comment by caoli5288** [comment]
或者你可以尝试把`bungee.mute`这个选项设置成`true`，强制关闭bungee通信

**Comment by nicklly** [comment]
确实。。问题已经解决了

然后还有个小问题 有玩家反馈说下线前一刻被打死，上线之后也是能复制物品

**Comment by caoli5288** [comment]
@nicklly 你的服是死亡掉落的吗，这我还真没测过相关的兼容性

**Comment by nicklly** [comment]
> @nicklly 你的服是死亡掉落的吗，这我还真没测过相关的兼容性

我服是打开死亡不掉落的

**Comment by nicklly** [comment]
> @nicklly 你的服是死亡掉落的吗，这我还真没测过相关的兼容性

能麻烦caoli复测咩.jpg（pls

**Comment by caoli5288** [comment]
感觉你这还是跟别的什么东西冲突了，我测试没问题 @nicklly

**Comment by nicklly** [comment]
![{ JBLT60)8}4)$A{SP}09RU](https://user-images.githubusercontent.com/17716585/130457537-9c740c78-26d9-4e11-87f3-ea306f1f8cd9.jpg)
测试完了。。发现是combatlogx的问题 调整过后就没问题 蟹蟹caoli (
