### ISSUE TITLE
This plugin requires simpleorm, but simpleorm is no longer available

### ISSUE THREAD

**Issue by YTiceice** [caoli5288/PlayerSQL#72]
This plugin requires simpleorm, but simpleorm is no longer available, please tell me the solution or fix this problem or change to use mysql api, mysql api plugin link: https://www.spigotmc.org/resources/mysql-api.23932/

**Comment by caoli5288** [comment]
https://github.com/caoli5288/SimpleORM

**Comment by YTiceice** [comment]
ok

caoli5288 ***@***.***> 於 2021年10月9日 週六 上午1:31寫道：
