### ISSUE TITLE
玩家数据被锁定

### ISSUE THREAD

**Issue by nicklly** [caoli5288/PlayerSQL#76]
![QQ截图20211016214635](https://user-images.githubusercontent.com/17716585/137589937-f10c908c-63bf-4104-8b12-9d229068fc43.png)
如图所示 新玩家一进来 就被秒踢出服务器了

插件版本：2.12.2
服务端：paper-1.12.2-1618
SimpleORM: 1.6.1

**Comment by caoli5288** [comment]
有无其他报错

**Comment by nicklly** [comment]
无

**Comment by caoli5288** [comment]
那应该是那个没有详细信息的NullPointerException导致的，没有详细信息很难帮到你
