### ISSUE TITLE
玩家背包物品/open

### ISSUE THREAD

**Issue by YTiceice** [caoli5288/PlayerSQL#78]
當我使用openinv插件並運行/open 玩家名(此玩家不在線上) 打開該玩家背包，並拿取他的一些物品，但是更改完畢後，玩家進入伺服器後會馬上死掉，並且將背包上的物品回復至運行 /open 玩家名 並拿取他的一些物品前的狀態
我想這應該是PlayerSQL的問題，因為原MYSQL上的玩家背包資料與更動後不同，所以導致強制玩家死亡，並將他背包的物品回復至玩家離開時的狀態(MYSQL儲存的狀態)
如果可以的話請將openinv的原代碼放置到此插件上，這樣就可以直接使用/open編輯PlayerSQL在MYSQL儲存的玩家資料

**Comment by caoli5288** [comment]
你为何不去openinv插件要求它兼容我的playersql呢？
